<?php

/**
 * @file
 * Contains ma_feedback_form.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ma_feedback_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ma_feedback_form module.
    case 'help.page.ma_feedback_form':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to manage feedback form through a Block') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 *
 * TODO:update
 */
function ma_feedback_form_page_attachments(array &$attachments) {

  // TODO:update
  $attachments['#attached']['library'][] = 'ma_feedback_form/feedback-form-css';

}