<?php

/**
 * @file
 * Contains mass_search.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mass_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mass_search module.
    case 'help.page.mass_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Embeds google custom search engine elements (forms, results, promotions, autocomplete) using javascript') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 * Define mass_search module twig template for search results page
 * Called in massgov_search module DefaultController
 *
 * @param  array  $existing  existing implementations
 * @param  string $type      what is being processed (theme, module, etc.)
 * @param  string $theme     the actual name of the theme, module, etc.
 * @param  string $path      the directory path of the theme or module
 * @return array             associative array of info about the implementation
 */
function mass_search_theme($existing, $type, $theme, $path) {
  return array(
    'mass_search' => array(
      'variables' => array('test_var' => NULL ),
    ),
  );
}
