<?php

/**
 * @file
 * Contains ma_feedback_form.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mass_feedback_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ma_feedback_form module.
    case 'help.page.ma_feedback_form':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to manage feedback form through a Block') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 *
 * Define twig template for feedback form block, called by PageFeedbackForm.
 */
function mass_feedback_form_theme() {
  return array(
      'block__mass_feedback_form' => array(
          'render element' => 'elements',
          'template' => 'block--mass-feedback-form',
          'base hook' => 'block'
      )
  );
}
