<?php

/**
 * @file
 * Contains mass_entityreference.module.
 *
 * Copyright 2016 Palantir.net, Inc.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mass_entityreference_form_node_subtopic_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Save current nid as a cookie so it can be accessed by entityreference.
  $node_id = \Drupal::routeMatch()->getRawParameter('node');
  user_cookie_save(['subtopic_nid' => $node_id]);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mass_entityreference_form_node_topic_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Save current nid as a cookie so it can be accessed by entityreference.
  $node_id = \Drupal::routeMatch()->getRawParameter('node');
  user_cookie_save(['topic_nid' => $node_id]);
}
